version: '3'

services:
  # Mongo db for local dev. For simplicity, password and username is omitted
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  # REST API SERVICE
  rest_api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    command: npm run dev
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    env_file: .env

volumes:
  mongo_db:
